#
# This class is automatically generated by mig. DO NOT EDIT THIS FILE.
# This class implements a Python interface to the 'QueryPacket'
# message type.
#

import tinyos.message.Message

# The default size of this message type in bytes.
DEFAULT_MESSAGE_SIZE = 7

# The Active Message type associated with this message.
AM_TYPE = 6

class QueryPacket(tinyos.message.Message.Message):
    # Create a new QueryPacket of size 7.
    def __init__(self, data="", addr=None, gid=None, base_offset=0, data_length=7):
        tinyos.message.Message.Message.__init__(self, data, addr, gid, base_offset, data_length)
        self.amTypeSet(AM_TYPE)
    
    # Get AM_TYPE
    def get_amType(cls):
        return AM_TYPE
    
    get_amType = classmethod(get_amType)
    
    #
    # Return a String representation of this message. Includes the
    # message type name and the non-indexed field values.
    #
    def __str__(self):
        s = "Message <QueryPacket> \n"
        try:
            s += "  [sampling_period=0x%x]\n" % (self.get_sampling_period())
        except:
            pass
        try:
            s += "  [query_lifetime=0x%x]\n" % (self.get_query_lifetime())
        except:
            pass
        try:
            s += "  [propagation_mode=0x%x]\n" % (self.get_propagation_mode())
        except:
            pass
        return s

    # Message-type-specific access methods appear below.

    #
    # Accessor methods for field: sampling_period
    #   Field type: int
    #   Offset (bits): 0
    #   Size (bits): 16
    #

    #
    # Return whether the field 'sampling_period' is signed (False).
    #
    def isSigned_sampling_period(self):
        return False
    
    #
    # Return whether the field 'sampling_period' is an array (False).
    #
    def isArray_sampling_period(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'sampling_period'
    #
    def offset_sampling_period(self):
        return (0 / 8)
    
    #
    # Return the offset (in bits) of the field 'sampling_period'
    #
    def offsetBits_sampling_period(self):
        return 0
    
    #
    # Return the value (as a int) of the field 'sampling_period'
    #
    def get_sampling_period(self):
        return self.getUIntElement(self.offsetBits_sampling_period(), 16, 1)
    
    #
    # Set the value of the field 'sampling_period'
    #
    def set_sampling_period(self, value):
        self.setUIntElement(self.offsetBits_sampling_period(), 16, value, 1)
    
    #
    # Return the size, in bytes, of the field 'sampling_period'
    #
    def size_sampling_period(self):
        return (16 / 8)
    
    #
    # Return the size, in bits, of the field 'sampling_period'
    #
    def sizeBits_sampling_period(self):
        return 16
    
    #
    # Accessor methods for field: query_lifetime
    #   Field type: long
    #   Offset (bits): 16
    #   Size (bits): 32
    #

    #
    # Return whether the field 'query_lifetime' is signed (False).
    #
    def isSigned_query_lifetime(self):
        return False
    
    #
    # Return whether the field 'query_lifetime' is an array (False).
    #
    def isArray_query_lifetime(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'query_lifetime'
    #
    def offset_query_lifetime(self):
        return (16 / 8)
    
    #
    # Return the offset (in bits) of the field 'query_lifetime'
    #
    def offsetBits_query_lifetime(self):
        return 16
    
    #
    # Return the value (as a long) of the field 'query_lifetime'
    #
    def get_query_lifetime(self):
        return self.getUIntElement(self.offsetBits_query_lifetime(), 32, 1)
    
    #
    # Set the value of the field 'query_lifetime'
    #
    def set_query_lifetime(self, value):
        self.setUIntElement(self.offsetBits_query_lifetime(), 32, value, 1)
    
    #
    # Return the size, in bytes, of the field 'query_lifetime'
    #
    def size_query_lifetime(self):
        return (32 / 8)
    
    #
    # Return the size, in bits, of the field 'query_lifetime'
    #
    def sizeBits_query_lifetime(self):
        return 32
    
    #
    # Accessor methods for field: propagation_mode
    #   Field type: short
    #   Offset (bits): 48
    #   Size (bits): 8
    #

    #
    # Return whether the field 'propagation_mode' is signed (False).
    #
    def isSigned_propagation_mode(self):
        return False
    
    #
    # Return whether the field 'propagation_mode' is an array (False).
    #
    def isArray_propagation_mode(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'propagation_mode'
    #
    def offset_propagation_mode(self):
        return (48 / 8)
    
    #
    # Return the offset (in bits) of the field 'propagation_mode'
    #
    def offsetBits_propagation_mode(self):
        return 48
    
    #
    # Return the value (as a short) of the field 'propagation_mode'
    #
    def get_propagation_mode(self):
        return self.getUIntElement(self.offsetBits_propagation_mode(), 8, 1)
    
    #
    # Set the value of the field 'propagation_mode'
    #
    def set_propagation_mode(self, value):
        self.setUIntElement(self.offsetBits_propagation_mode(), 8, value, 1)
    
    #
    # Return the size, in bytes, of the field 'propagation_mode'
    #
    def size_propagation_mode(self):
        return (8 / 8)
    
    #
    # Return the size, in bits, of the field 'propagation_mode'
    #
    def sizeBits_propagation_mode(self):
        return 8
    
